# Compression configuration for RCC pipeline
cascade:
  stages:
    - name: "dare"
      config:
        target_sparsity: 0.9
        num_iterations: 10
        schedule: "cosine"
        fine_tune_epochs: 5
        importance_metric: "magnitude"
        rescale_weights: true
        block_size: null
        iterative_pruning: true

    - name: "nullu"
      config:
        rank_reduction_ratio: 0.5
        energy_threshold: 0.95
        decomposition_method: "svd"
        min_rank: 1
        layer_wise_adaptation: true
        use_randomized_svd: true
        power_iterations: 2
        preserve_null_space: true

    - name: "alphaedit"
      config:
        learning_rate: 0.001
        num_epochs: 10
        importance_metric: "gradient"
        regularization: 0.001
        use_fisher_information: true
        fisher_num_samples: 1000
        alpha_momentum: 0.9
        min_alpha: 0.1
        max_alpha: 10.0
        temperature: 1.0

  validation:
    performance_threshold: 0.95
    rollback_enabled: true
    checkpoint_frequency: 1
    max_performance_drop: 0.05